### PR TITLE
Fixed line width measuring

### PR DESCRIPTION
**Pull request by samskiter**
Tested on a Nexus 5 running lollipop with a variety of texts in a textview.

### CODE REVIEW

**Comment by AndroidDeveloperLB** [comment]
Can you please show me a screenshot or something, of the issue itself? or a way to reproduce it?
Also, sadly, this doesn't seem to fix the issue I've found and written about, that the last letter of the current line can go to the next line.

**Comment by samskiter** [comment]
@AndroidDeveloperLB Appologies for not being clear, this relates to the issue i raised about text not filling: https://github.com/AndroidDeveloperLB/AutoFitTextView/issues/11

The other issue i raised (#12), i think contains a solution to your other problem.

I'll try and get you a screenshot of the issue. But basically, the text is coming out far smaller than it could be on a square-ish textview. I'll probably also have to test on another device with an older version of android.

Could you try this and see if it breaks anything your end?

**Comment by samskiter** [comment]
Before:
https://www.dropbox.com/s/rty07vxwmngvxsa/text_before.png?dl=0
After (with this fix applied):
https://www.dropbox.com/s/kmeg2vhejyz09eo/text_after.png?dl=0

Note that both textviews have some padding but similar results are observed without the padding. (In fact that was the situation I found this in)

**Comment by AndroidDeveloperLB** [comment]
I'm not sure what has happened here. You've create 3 thread about one issue? why didn't you just write it on the same thread?
The code you've written is the same as what you are suggesting here, and I've still noticed the issue I've written about.
Anyway, I'll now merge the pull request. Thank you for contributing.

**Comment by samskiter** [comment]
#12 Is about casting an int.

This MR is about using a different API to measure line widths.

The approach on Github is generally to have one MR per issue. If for example, this MR caused a bug, we'd still have the issue open to track the problem.

**Comment by AndroidDeveloperLB** [comment]
ok, here's the issue I'm talking about:
https://github.com/AndroidDeveloperLB/AutoFitTextView/issues/15

**Pull request merged**
